### PR TITLE
Fix #15 and replace deprecated variables

### LINKED ISSUE #15: Python3 not detected on Ubuntu 20.04
Hello!

I've just been testing this role as part of a project and found that it was unable to detect python3 on Ubuntu 20.04, looking into the reasoning behind this, I found that the ansible_python_interpreter variable was not being set.

```
TASK [fauust.mariadb : Install python mariadb driver] ******************************************************************
fatal: [172.16.0.50]: FAILED! => {"changed": false, "msg": "No package matching 'python-pymysql' is available"}
fatal: [172.16.0.51]: FAILED! => {"changed": false, "msg": "No package matching 'python-pymysql' is available"}

PLAY [Hostvars debug] **************************************************************************************************
TASK [Gathering Facts] *************************************************************************************************
ok: [172.16.0.50]
ok: [172.16.0.51]

TASK [DEBUG HOSTVARS] **************************************************************************************************
ok: [172.16.0.50] => {
    "ansible_python_interpreter": "VARIABLE IS NOT DEFINED!"
}
ok: [172.16.0.51] => {
    "ansible_python_interpreter": "VARIABLE IS NOT DEFINED!"
}
```

I did however find that ansible_python.executable _is_ being set.
```
PLAY [Hostvars debug] **************************************************************************************************
TASK [Gathering Facts] *************************************************************************************************
ok: [172.16.0.51]
ok: [172.16.0.50]

TASK [DEBUG HOSTVARS] **************************************************************************************************
ok: [172.16.0.50] => {
    "ansible_python.executable": "/usr/bin/python3"
}
ok: [172.16.0.51] => {
    "ansible_python.executable": "/usr/bin/python3"
}
```

Changing [tasks/setup.yml#L33](https://github.com/fauust/ansible-role-mariadb/blob/89695a699fb2f0bb05901a78624683c9069d2e18/tasks/setup.yml#L33) to use this ansible_python.executable variable, the playbook ran from start to finish without a hitch.

I'm unsure if this is an Ubuntu 20.04 or Ansible 2.12 issue, but figured it would be worth bringing up regardless. I do not imagine my fix to be a good one, and I'm sure there's a more reliable way of detecting the correct version.

ansible --version output attached in the interest of preserving all details:
```
ansible [core 2.12.1]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

### PR DESCRIPTION
**Pull request by TheGuyDanish**
As discussed, moving from `ansible_python_interpreter` to `discovered_interpreter_python`. 

And while I'm at it, /s/slave/replica/g to get rid of the deprecation warnings.

### CODE REVIEW

**Comment by fauust** [comment]
> As discussed, moving from `ansible_python_interpreter` to `discovered_interpreter_python`.

Thanks!

> And while I'm at it, /s/slave/replica/g to get rid of the deprecation warnings.

Good! What about `slave_pos` I believe it could be changed too.

Finally, can you verify why the check did not pass? (I have activated them you should now have them run anytime you push).

**Comment by TheGuyDanish** [comment]
> > And while I'm at it, /s/slave/replica/g to get rid of the deprecation warnings.
> 
> Good! What about `slave_pos` I believe it could be changed too.

I don't believe these need to be changed yet, as per the module itself:
```
"deprecations": [
  {
    "collection_name": "community.mysql",
    "msg": "\"Is_Master\" and \"Is_Slave\" return values are deprecated and will be replaced with \"Is_Primary\" and \"Is_Replica\" in the next major release. Use \"Is_Primary\" and \"Is_Replica\" instead.",
    "version": "3.0.0"
  }
],
```

Other lines don't seem to be changing just yet. The variables for the Slave IO and Slave SQL threads are also kept for now.
```
"Slave_IO_Running": "Yes",
"Slave_IO_State": "Waiting for master to send event",
"Slave_Non_Transactional_Groups": 0,
"Slave_SQL_Running": "Yes",
"Slave_SQL_Running_State": "Slave has read all relay log; waiting for the slave I/O thread to update it",
```

For now though, these seem to run fine, so I'm not too worried about them.

Looking into the tests now, though oddly, they seem to fail for the same reason as the prior version. I'm unsure why tests failed as that variable shouldn't be of any relevance anymore. Regardless, I've removed it in my last push and tested on my local machine to great success.

```PLAY RECAP *************************************************************************************************************
172.16.0.51                : ok=15   changed=10   unreachable=0    failed=0    skipped=8    rescued=0    ignored=0```

**Comment by TheGuyDanish** [comment]
(Looks like it still needs you to approve the workflow too. I guess until it's merged, I'm still a 'first-time contributor'.)

**Comment by fauust** [comment]
> (Looks like it still needs you to approve the workflow too. I guess until it's merged, I'm still a 'first-time contributor'.)

Oh, I didn't know, sorry for that. Is there any reason why the CI does not run on you fork? I did not received too much contribution on this project so this was not tested too much and there is probably something that is missing in the GitHub workflow/conf.

**Comment by fauust** [comment]
> > > And while I'm at it, /s/slave/replica/g to get rid of the deprecation warnings.
> > 
> > 
> > Good! What about `slave_pos` I believe it could be changed too.
> 
> I don't believe these need to be changed yet, as per the module itself:
> 
> ```
> "deprecations": [
>   {
>     "collection_name": "community.mysql",
>     "msg": "\"Is_Master\" and \"Is_Slave\" return values are deprecated and will be replaced with \"Is_Primary\" and \"Is_Replica\" in the next major release. Use \"Is_Primary\" and \"Is_Replica\" instead.",
>     "version": "3.0.0"
>   }
> ],
> ```
> 
> Other lines don't seem to be changing just yet. The variables for the Slave IO and Slave SQL threads are also kept for now.

You are right!
That would remove support for older MariaDB versions:

From https://docs.ansible.com/ansible/latest/collections/community/mysql/mysql_replication_module.html
> `replica_pos` has been introduced in MariaDB 10.5.1 and it is an alias for `slave_pos`.

**Comment by TheGuyDanish** [comment]
> > (Looks like it still needs you to approve the workflow too. I guess until it's merged, I'm still a 'first-time contributor'.)
> 
> Oh, I didn't know, sorry for that. Is there any reason why the CI does not run on you fork? I did not received too much contribution on this project so this was not tested too much and there is probably something that is missing in the GitHub workflow/conf.

A good question, really. I'd love to answer it, but I'm more of a sysad than a developer myself, so my CI knowledge is lacking at best. 😂

Regardless, this seems to pass the PR CI now.
https://github.com/fauust/ansible-role-mariadb/runs/5049014611?check_suite_focus=true

**Comment by fauust** [comment]
Excellent!

Can I finally ask you to squash your commits in one nice commit :pray:

Gentle recommendation for your git commits:
- try to explain the why not the what (that is visible in your commits ;)).
- this is a good reading IMO too: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by TheGuyDanish** [comment]
My commit messages are functional, not pretty. ;)

Jokes aside, squashed them now, hope that's more to your liking.

**Pull request merged**
